# Generated by Django 4.1.3 on 2022-11-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=2048)),
                ('note', models.CharField(max_length=20480)),
            ],
        ),
    ]
